services:
  ui:
    image: ghcr.io/mai0313/automotive-ui:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: prod
    command:
      - npm
      - run
      - web
    ports:
      - 8081:8081
    volumes:
      - ./.env:/app/.env
    pull_policy: always
    restart: always

  ws:
    image: ghcr.io/mai0313/automotive-ui:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: prod
    command:
      - npm
      - run
      - ws
    ports:
      - 4000:4000
      - 4001:4001
    volumes:
      - ./.env:/app/.env
    pull_policy: always
    restart: always
